### ISSUE TITLE
`async fn` is not permitted in the 2015 edition

### ISSUE THREAD

**Issue by Powaful3000** [dank/tarkov#13]
Installed everything on WSL, cargo build executes no problem, running rustc auth_basic.rs throws

error[E0670]: `async fn` is not permitted in the 2015 edition
 --> auth_basic.rs:5:1
  |
5 | async fn main() -> Result<(), Error> {
  | ^^^^^

error[E0433]: failed to resolve: maybe a missing crate `tarkov`?
 --> auth_basic.rs:1:5
  |
1 | use tarkov::hwid::generate_hwid;
  |     ^^^^^^ maybe a missing crate `tarkov`?

error[E0432]: unresolved import `tarkov`
 --> auth_basic.rs:2:5
  |
2 | use tarkov::{Error, Tarkov};
  |     ^^^^^^ maybe a missing crate `tarkov`?

error[E0433]: failed to resolve: use of undeclared type or module `actix_rt`
 --> auth_basic.rs:4:3
  |
4 | #[actix_rt::main]
  |   ^^^^^^^^ use of undeclared type or module `actix_rt`

error[E0433]: failed to resolve: use of undeclared type or module `env_logger`
 --> auth_basic.rs:7:5
  |
7 |     env_logger::init();
  |     ^^^^^^^^^^ use of undeclared type or module `env_logger`

error[E0425]: cannot find function `generate_hwid` in this scope
 --> auth_basic.rs:9:57
  |
9 |     let t = Tarkov::login("me@example.com", "password", generate_hwid().as_str()).await?;
  |                                                         ^^^^^^^^^^^^^ not found in this scope     
error[E0425]: cannot find function `generate_hwid` in this scope
  --> auth_basic.rs:14:9
   |
14 |         generate_hwid().as_str(),
   |         ^^^^^^^^^^^^^ not found in this scope

error[E0277]: `main` has invalid return type `impl std::future::Future`
 --> auth_basic.rs:5:20
  |
5 | async fn main() -> Result<(), Error> {
  |                    ^^^^^^^^^^^^^^^^^ `main` can only return types that implement `std::process::Termination`
  |
  = help: consider using `()`, or a `Result`

error: aborting due to 8 previous errors

Some errors have detailed explanations: E0277, E0425, E0432, E0433, E0670.
For more information about an error, try `rustc --explain E0277`.

**Comment by dank** [comment]
```
rustup update stable
```

You need Rust 1.40 and edition 2018 (but I'm not quite sure how you update that?).

**Comment by WCharacter** [comment]
I have the same issue on rustc 1.40.0 (73528e339 2019-12-16)

**Comment by dank** [comment]
Don't use `rustc`.

Read about `cargo`: https://doc.rust-lang.org/cargo/

To run an example:
```
cargo run --example auth_basic
```
