### ISSUE TITLE
No connections available error

### ISSUE THREAD

**Issue by WCharacter** [dank/tarkov#14]
I got this error when try to launch example of auth_basic. 
`Error: SendRequestError(Connect(Resolver(ResolveError { inner: ProtoError { inner:
No connections available }
proto error })))`

**Comment by dank** [comment]
How can I reproduce this?

**Comment by dank** [comment]
This is a network issue related to the [actix](https://github.com/actix/actix-web) library. Make sure you don't have any firewalls, VPN or proxies that may be blocking traffic.
