### ISSUE TITLE
How profitable is it to use this?

### ISSUE THREAD

**Issue by rikato** [dank/tarkov#17]
I was just wondering if you could tell me how much you make using this?

**Comment by dank** [comment]
The devs changed how the market works this morning, I haven't really had a chance to test it out but yesterday I was making about 4mil in 30 minutes. Although it's all gonna depend on the bot you write with this crate.

**Comment by rikato** [comment]
Wow okay so it's profitable if you know how to wirte a good trading bot on top of your library. What did they change anyhting game breaking?

**Comment by rikato** [comment]
Ah i found it they removed the delay. Hmm I guess it will be harder now to limit the amount of requests since you'll have to keep checking for items now.
