### ISSUE TITLE
Automatically Receiving All?

### ISSUE THREAD

**Issue by lflare** [dank/tarkov#20]
It seems that you reply really fast, my apologies for yet another issue.

What would be the best way to automatically receive all items from a trader?

**Comment by dank** [comment]
Please refer to the docs for simple questions like this: https://docs.rs/tarkov

You have to get all the traders with `get_traders` and get their items by `get_trader_items`.

**Comment by lflare** [comment]
That's not the point of my question though. `get_trader_items` is for getting the list of items for sale right? I'm trying to automatically receive items in the mail, either from insurance or flea market.

**Comment by dank** [comment]
Oh, that’s not supported yet. I want to handle the messenger eventually.
