### ISSUE TITLE
Provide example showing how to use captcha-harvester in combination with this?

### ISSUE THREAD

**Issue by garrettjoecox** [dank/tarkov#22]
I'm mostly wondering what properties I'm supposed to provide to the Captcha Harvester linked on the README.

- Sitekey
- Solve URL
- Captcha Window Port
- Server Bank Port

**Comment by dank** [comment]
Sitekey and solve URL can change so I don't want to include that, you can find it by reversing the launcher or sniffing its traffic when logging in.

Captcha window port and server bank port is irrelevant, set it to whatever you want or leave it default.

**Comment by rezicG** [comment]
Would you mind giving me any pointers as to what tools I would need to sniff and read the traffic to get Sitekey and solve URL? Is Wireshark enough when it's encrypted?
