### ISSUE TITLE
Help with certificate pinning?

### ISSUE THREAD

**Issue by garrettjoecox** [dank/tarkov#25]
Hey there, interested in reverse engineering more of the API and extending off of this repo but I’m kind of a beginner in this realm, any pointers in how to get around the certificate pinning so I can sniff the in game traffic? How were you able to determine the in game endpoints and payloads to send (with the ragfair and market for example)

**Comment by dank** [comment]
You can’t without bypassing Battleye. It’s easier to reverse the game code and find where they are calling these APIs.

**Comment by garrettjoecox** [comment]
Ah figures... I'll start digging into that then, thanks.

**Comment by Nulled2117** [comment]
> Hey there, interested in reverse engineering more of the API and extending off of this repo but I’m kind of a beginner in this realm, any pointers in how to get around the certificate pinning so I can sniff the in game traffic? How were you able to determine the in game endpoints and payloads to send (with the ragfair and market for example)

Also you can just Just Emu-Tarkov to get a good idea on how the API works as well 👍

**Comment by garrettjoecox** [comment]
@dank any pointers on reversing the game code? I've been digging around using ILSpy, and all I was able to find was some references to a BackendConfig, but wasn't able to trace that to anything useful.. And all the strings seem to be obfuscated unless I'm doing something wrong >.<

**Comment by dank** [comment]
@garrettjoecox,

You can use tools like [de4dot](https://github.com/0xd4d/de4dot) to deobfuscate .NET code.

Also, try to see how Unity works. Here's a good place to start for web requests: https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.html

Then you can look for where the game might be calling these Unity APIs.

**Comment by garrettjoecox** [comment]
Great, thanks!

**Comment by garrettjoecox** [comment]
@dank So I was able to get it deobfuscated, including passing the method token to de4dot and that's been very helpful. There still seems to be a level of obfuscation around the class names however, most of them are named GClass### or Class###. Is there a de4dot option I'm missing for this, or was the original class name information lost in obfuscation?

**Comment by dank** [comment]
That’s the best you’ll get because the .NET compiler doesn’t preserve class and method names I think.
