### ISSUE TITLE
Error: LoginError(BadTwoFactorCode)

### ISSUE THREAD

**Issue by rezicG** [dank/tarkov#27]
Hey, I'm trying to authenticate using login_with_2fa, but keep running into 

> Error: LoginError(BadTwoFactorCode).

I've added io:stdin().read_line so that I can input the 2FA manually.
I'm unable to figure  out why this fails.. Do you have any suggestions?

Sorry if an issue isn't the the best place to ask this, but Google hasn't been kind to me on this one..

**main.rs:**
`use tarkov::auth::LoginError;
use tarkov::hwid::generate_hwid;
use tarkov::{Error, Tarkov};
use std::io;

#[tokio::main]
async fn main() -> Result<(), Error> {
    std::env::set_var("RUST_LOG", "tarkov=info");

    let email = "einar_weltan@hotmail.com";
    let password = "7G79Wn!$WTM0G5";
    let hwid = generate_hwid();

    let t = match Tarkov::login(email, password, &hwid).await {
        Ok(t) => Ok(t),
        Err(Error::LoginError(e)) => match e {
            // 2FA required!
            LoginError::TwoFactorRequired => {
                // Get 2FA from email (or generate TOTP) then continue...
				let mut code = String::new();
				println!("Hardware ID: {}", &hwid);
				println!("Input 2FA:");
				io::stdin().read_line(&mut code).expect("Failed to read input");
				println!("{}", &code);
                Tarkov::login_with_2fa(email, password, &code, &hwid).await
            }
            _ => Err(e)?,
        },
        Err(e) => Err(e),
    }?;

    println!("{}", t.session);

    Ok(())
}`

**Cargo.toml:**
`[package]
name = "eft_market"
description = "Idk yet"
version = "0.1.0"
authors = ["Dan Kyung <dan@kyung.ca>"]
edition = "2018"

[dependencies]
md5 = "0.7"
err-derive = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
rand = "0.7"
log = "0.4"
serde_repr = "0.1"
hyper = "0.13"
hyper-tls = "0.4"
http = "0.2"
tarkov = { path = "./tarkov-master" }
tokio = { version = "0.2.6", features = ["full"] }`

**rustc version: 1.41.0**

**Comment by dank** [comment]
`read_line` appends `\n` to the input.
