### ISSUE TITLE
Have a way to inspect attachments on items in ragfair?

### ISSUE THREAD

**Issue by Esya** [dank/tarkov#30]
Hey,

Browsed the code, and even though I do not use Rust, it's super clean! Do you plan on adding a way to inspect the mods and attachment for a weapon (or generally any item) ?

It would seem that [this line](https://github.com/dank/tarkov/blob/5b7f929b16d3b87751125444b951349e352e0d13/src/inventory.rs#L54) covers it in your `Item` struct but the `Upd` struct does not seem to reflect that

Thanks !

**Comment by dank** [comment]
`Upd` is more for item settings or attachment settings, I should clarify the docs. 

Attachments can be found with `parent_id` or `slot_id` (I forgot whoops), they correspond to the weapon ID.
