### ISSUE TITLE
profile is locked

### ISSUE THREAD

**Issue by adamburgess** [dank/tarkov#31]
just wondering if you've encountered this error from RagFairBuyOffer?

```
{
  error: {
    err: 228,
    errmsg: '228 - ItemsMoving: profile [my pmc's profile id here] is locked',
    data: []
  }
}
```

You added an error 228 from f3f319034fcc4e27b400d98c08dddb4622f8f9c1 and I was wondering if it's the same error and you added a more descriptive reason.

note: not using _your_ library (reimplemented it in TS). logged back into the game and everything functions normally.

**Comment by dank** [comment]
I’ve never seen that message before but usually error 228 means you sent the wrong items to trade. Make sure your parameters are correct, can’t comment on your code because I don’t have it.
