### ISSUE TITLE
How to get the price a trader is giving me for a specific item?

### ISSUE THREAD

**Issue by willysteht** [dank/tarkov#34]
Hi,

is there a way to get the money a Trader wants to give me for a specific item?

Thanks!

**Comment by dank** [comment]
https://docs.rs/tarkov/0.1.1/tarkov/struct.Tarkov.html#method.get_trader_items

**Comment by willysteht** [comment]
Ya found that before but it seemed to give me just the items the Trader is selling. 
Will try it in a few hours when I'm home.

**Comment by dank** [comment]
https://docs.rs/tarkov/0.1.1/tarkov/struct.Tarkov.html#method.get_item_prices

Misunderstood your question sorry

**Comment by rHermes** [comment]
The get_item_prices returns just a map from an item to a price. It is not really for a single trader and the prices are wrong. Take the example of a lvl 1 dogtag vs a level 50 one. Right now the sell_item function seems to be a oneshot operation. Is there any API endpoint for checking the price for a specific item against a specific trader?
