### ISSUE TITLE
Is this still relevant

### ISSUE THREAD

**Issue by samuelkampf** [dank/tarkov#39]
Hi i wondering will this stiill interact with the api i have attempted sniffing the game itself but it uses updated tls encryption now. Does this library still work?

**Comment by dank** [comment]
Should work. The TLS encryption you’re talking about is just SSL. You can use a trusted root cert to sniff local SSL traffic. 

https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/DecryptHTTPS
