### ISSUE TITLE
How to get session from EFT launcher?

### ISSUE THREAD

**Issue by nisaev** [dank/tarkov#41]
I can't auth. I've tried to sniffing traffic from EFT client, but it's HTTPS with cerificate verification. When I'm trying to use Charles for example - I got error in EFT client (Certificate invalid).

**Comment by dank** [comment]
The game won’t let you sniff traffic because of a security feature called “certificate pinning”. Unless they added that to the launcher recently (I don’t know because I haven’t played in a bit) you should be able to grab the session from the launcher.

**Comment by nisaev** [comment]
«you should be able to grab the session from the launcher.»
I’m Sorry, how?  I Hope you will update information on GitHub how to do it.
Thank you
  
>Пятница, 28 февраля 2020, 23:49 +03:00 от Dan Kyung <notifications@github.com>:
> 
>The game won’t let you sniff traffic because of a security feature called “certificate pinning”. Unless they added that to the launcher recently (I don’t know because I haven’t played in a bit) you should be able to grab the session from the launcher.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Никита Исаев
n_isaev@bk.ru

**Comment by dank** [comment]
@nisaev sniff the EFT launcher traffic with Fiddler or Charles. The session is in the traffic.
