### ISSUE TITLE
Got "UnknownAPIError(232)"

### ISSUE THREAD

**Issue by nisaev** [dank/tarkov#43]
Finally I've grab token+hardware id from EFT Launcher.
Now, when I'm trying to auth with this I'm getting "UnknownAPIError(232)".
I used "from_access_token" from "auth_basic" example
Looks like developer changed api?

**Comment by nisaev** [comment]
Fixed by changing game version in lib.rs

**Comment by aidenstern** [comment]
how exactly did you fix this? im having the same error

**Comment by dank** [comment]
@aidenstern This is fixed in master. I'll publish a new version today.

**Comment by dank** [comment]
@aidenstern pushed version 0.1.4
