### ISSUE TITLE
failed to resolve: could not find `___rt` in quote

### ISSUE THREAD

**Issue by aidenstern** [dank/tarkov#47]
I created a new project to use this library. I set a new dependency in `cargo.toml` as `tarkov = "0.1"` and then in my `main.rs` file I only have a basic println function.

When I run this, no matter what I put in that file, it will work fine without the tarkov dependency but break as soon as I put it back. I get back this error:

```
C:/Users/Aiden/.cargo/bin/cargo.exe run --color=always --package tarkovbot --bin tarkovbot
   Compiling err-derive v0.2.2
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> C:\Users\Aiden\.cargo\registry\src\github.com-1ecc6299db9ec823\err-derive-0.2.2\src\lib.rs:203:56
    |
203 | fn display_body(s: &synstructure::Structure) -> quote::__rt::TokenStream {
    |                                                        ^^^^ could not find `__rt` in `quote`

error: aborting due to previous error
```

**Comment by aidenstern** [comment]
I've tried using cargo update and an earlier dependency of `quote` as suggested in this post: 

https://users.rust-lang.org/t/failure-derive-compilation-error/39062/19

doesn't change

**Comment by dank** [comment]
This is a bug in the `err-derive` crate. Looks like they fixed this very recently: https://gitlab.com/torkleyy/err-derive/-/commit/33c0d9aa6476c93558c9c50a11696b483f2cfe2c

I'm guessing crates.io hasn't been updated yet. Try `cargo clean` in a few minutes. 

I'll lock down the crate versions in the future to prevent this.

**Comment by dank** [comment]
Running `cargo update` in your project should fix this. Just tested it locally.
