### ISSUE TITLE
JSON Error - Invalid Type Integer

### ISSUE THREAD

**Issue by baby** [dank/tarkov#55]
I'm getting this error whenever I try to buy items from the flea market
```
Error: Json(Error("invalid type: integer `6932509`, expected a string", line: 1, column: 91))
```
I'm thinking maybe an endpoint has changed? I'm not too sure, I've been messing with it for a few hours and haven't been able to figure out whats wrong.

This happens when following the flea market buying example.

**Comment by baby** [comment]
Fixed it by changing int_id from a string to a u64 in the Offer struct in ragfair.rs.

```rs
/// ragfair.rs
pub struct Offer {
    ...
    /// Changed from String to u64
    pub int_id: u64,
    ...
}
```

**Comment by dank** [comment]
Thanks, I'll fix this on master soon.
