### ISSUE TITLE
Character level restrictions

### ISSUE THREAD

**Issue by egracens** [dank/tarkov#57]
Hello everyone!
In the current version of the game, I cannot get access to the flea marketplace until I reach 10 lvl.
I wondering is it possible to buy the standard game edition with 1 lvl character and use this tool to collect item prices on the flea market with 1 lvl game account? In this way, I am trying to prevent ban of my primary account.

**Comment by Nothing4You** [comment]
fwiw if you do this it greatly increases likelyhood of getting banned

**Comment by dank** [comment]
I don’t think this is possible at all, you are probably locked out of flea market until lvl 10.
